name: "Deployment Workflow"
on: 
    push:
        branches:
            - main



jobs: 
    simple_deploy:
        runs-on: ubuntu-latest
        steps:
        - name: "Checkouts out"
          uses: actions/checkout@v4

        
        - name: Generate random numbers
          id: random
          run: |
              random_number=$((1 + RANDOM))
        
        - name: "Build the image"
          run: |
                sudo docker build -t abatan/bik_latest:$random_number frontend/

        - name: "Login to Docker Hub"
          uses: docker/login-action@v3
          with: 
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
            
        - name: "Push the image to DockerHub"
          run: |
                docker push abatan/bik_latest:$random_number

                


            

