name: "Deployment Workflow"
on: 
    push:
        branches:
            - main


env:
  APP_VERSION: 126
jobs: 
    simple_deploy:
        runs-on: ubuntu-latest
        steps:
        - name: "Checkouts out"
          uses: actions/checkout@v4
        
        - name: "Build the image"
          run: |
                sudo docker build -t abatan/bik_latest:$APP_VERSION frontend/

        - name: "Login to Docker Hub"
          uses: docker/login-action@v3
          with: 
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
            
        - name: "Push the image to DockerHub"
          run: |
                docker push abatan/bik_latest:$APP_VERSION


            

